#!/bin/bash
v="1.21.0";

mv ffmpeg_neon/*/libffmpeg.mx.so libffmpeg.mx.so.neon.$v;
mv ffmpeg_arm64/*/libffmpeg.mx.so libffmpeg.mx.so.neon64.$v;
mv ffmpeg_tegra2/*/libffmpeg.mx.so libffmpeg.mx.so.tegra2.$v;
mv ffmpeg_tegra3/*/libffmpeg.mx.so libffmpeg.mx.so.tegra3.$v;
mv ffmpeg_x86_64/*/libffmpeg.mx.so libffmpeg.mx.so.x86_64.$v;
mv ffmpeg_x86/*/libffmpeg.mx.so libffmpeg.mx.so.x86.$v;

zip -9 -r mx_neon.zip libffmpeg.mx.so.neon.$v;
zip -9 -r mx_neon64.zip libffmpeg.mx.so.neon64.$v;
zip -9 -r mx_tegra2.zip libffmpeg.mx.so.tegra2.$v;
zip -9 -r mx_tegra3.zip libffmpeg.mx.so.tegra3.$v;
zip -9 -r mx_x86.zip libffmpeg.mx.so.x86.$v;
zip -9 -r mx_x86_64.zip libffmpeg.mx.so.x86_64.$v;
zip -9 -r mx_aio.zip libffmpeg.mx.so.x86.$v libffmpeg.mx.so.neon64.$v libffmpeg.mx.so.x86_64.$v libffmpeg.mx.so.tegra3.$v libffmpeg.mx.so.tegra2.$v libffmpeg.mx.so.neon.$v;
