void av_base64_decode();
void av_base64_encode();
void av_bitstream_filter_init();
void av_bitstream_filter_close();
void av_bitstream_filter_filter();
void av_buffersink_get_frame();
void av_buffersrc_add_frame_flags();
void avfilter_link();
void av_copy_packet();
void av_dict_count();
void av_dict_get();
void av_dict_set();
void av_dict_free();
void av_dump_format();
void av_find_best_stream();
void av_find_default_stream_index();
void av_find_program_from_stream();
void av_frame_alloc();
void av_frame_clone();
void av_frame_free();
void av_frame_is_writable();
void av_frame_ref();
void av_frame_unref();
void av_free();
void av_freep();
void av_get_bits_per_pixel();
void av_get_bytes_per_sample();
void av_get_bits_per_sample();
void av_get_channel_layout_nb_channels();
void av_get_codec_tag_string();
void av_get_default_channel_layout();
void av_grow_packet();
void av_guess_frame_rate();
void av_guess_sample_aspect_ratio();
void av_image_copy();
void av_init_packet();
void av_log();
void av_log_set_callback();
void av_malloc();
void av_mallocz();
void av_mallocz_array();
void av_new_packet();
void av_packet_copy_props();
void av_packet_ref();
void av_packet_unref();
void av_pix_fmt_count_planes();
void av_pix_fmt_desc_get();
void av_read_frame();
void av_read_pause();
void av_read_play();
void av_rescale();
void av_rescale_q();
void av_rescale_rnd();
void av_rescale_q_rnd();
void av_sample_fmt_is_planar();
void av_samples_get_buffer_size();
void av_seek_frame();
void av_shrink_packet();
void av_strdup();
void avcodec_close();
void avcodec_decode_subtitle2();
void avcodec_find_decoder();
void avcodec_flush_buffers();
void avcodec_get_name();
void avcodec_get_type();
// void avcodec_profile_name();
void av_get_profile_name();
void avcodec_open2();
void avformat_alloc_context();
void avformat_close_input();
void avformat_find_stream_info();
void avformat_network_init();
void avformat_open_input();
void avformat_seek_file();
void avfilter_inout_alloc();
void avfilter_inout_free();
void avfilter_get_by_name();
void avfilter_graph_alloc();
void avfilter_graph_config();
void avfilter_graph_create_filter();
void avfilter_graph_free();
void avfilter_graph_parse_ptr();
void avio_alloc_context();
void avio_flush();
void avio_size();
void avsubtitle_free();
void ff_check_interrupt();
void ff_add_format();
void ff_isom_write_hvcc();
void ff_isom_write_avcc();
void ff_isom_write_av1c();
void swr_alloc_set_opts();
void swr_convert();
void swr_free();
void swr_init();
void sws_freeContext();
void sws_getCachedContext();
void sws_scale();
// void ff_draw_init();
// void ff_draw_color();
// void ff_blend_mask();

void avcodec_whitelist();
void avcodec_send_packet();
void avcodec_receive_frame();
void avcodec_alloc_context3();
void avcodec_parameters_to_context();
void avcodec_parameters_alloc();
void avcodec_parameters_free();
void avcodec_free_context();
void av_dict_set_int();
void avcodec_profile_name();
void av_codec_set_pkt_timebase();
void ff_urldecode();
void av_md5_sum();

//export the api symbols for mxv
void av_stereo3d_alloc();
void av_stream_add_side_data();
void av_stream_get_side_data();
void av_aes_alloc();
void av_aes_init();
void av_aes_crypt();
void av_sha_alloc();
void av_sha_init();
void av_sha_update();
void av_sha_final();
void av_crc_get_table();
void av_crc();
void avio_read();
void avio_seek();
void avio_rb64();
void avio_rb32();
void avio_r8();
void avio_skip();
void ff_packet_list_get();
void ff_packet_list_free();
void ff_packet_list_put();
void av_packet_new_side_data();
void av_add_index_entry();
void av_index_search_timestamp();
void ff_update_cur_dts();
void av_realloc();
void av_malloc_array();
void av_realloc_array();
void av_lzo1x_decode();
void ffio_limit();
void ffio_fill();
void av_buffer_create();
void av_buffer_realloc();
void av_buffer_unref();
void av_buffer_ref();
void ffio_init_context();
void ff_reduce_index();
void ff_rm_reorder_sipr_data();
void avio_rl32();
void avpriv_report_missing_feature();
void avpriv_dict_set_timestamp();
void avpriv_mpeg4audio_sample_rates();
void avpriv_mpeg4audio_get_config();
void avpriv_split_xiph_headers();
void ff_vorbis_comment();
void avformat_new_stream();
void ff_codec_bmp_tags();
void ff_codec_get_id();
void ff_codec_get_tag();
void ff_get_wav_header();
void ff_codec_movvideo_tags();
void ff_codec_movaudio_tags();
void ff_codec_wav_tags();
void ff_put_wav_header();
void ff_put_bmp_header();
void avio_rb16();
void ff_sipr_subpk_size();
void ff_parse_creation_time_metadata();
void ff_stream_add_bitstream_filter();
void avio_write();
void avio_wl16();
void avio_wl32();
void avio_w8();
void avio_wb16();
void avio_wb32();
void avio_wb64();
void avio_printf();
void avio_write_marker();
void avio_open_dyn_buf();
void avio_get_dyn_buf();
void avio_close_dyn_buf();
void av_lfg_init();
void av_get_random_seed();
void av_fourcc_make_string();
void ff_get_qtpalette();
void avpriv_set_pts_info();
void ff_alloc_extradata();
void av_reduce();
void avcodec_chroma_pos_to_enum();
void av_content_light_metadata_alloc();
void av_stream_new_side_data();
void av_spherical_alloc();
void ff_alloc_extradata();
void avformat_new_stream();
void avpriv_new_chapter();
void av_strlcpy();
void av_strlcat();
void av_strcasecmp();
void ff_metadata_conv();
void ff_metadata_conv_ctx();
void ff_flac_is_native_layout();
void ff_flac_write_header();
void ff_vorbiscomment_length();
void ff_vorbiscomment_write();
void ff_convert_lang_to();
void ff_hevc_annexb2mp4_buf();
void ff_wv_parse_header();
void ff_avc_parse_nal_units_buf();
void ff_av1_filter_obus_buf();
extern unsigned char ff_log2_tab[256];
void av_reallocp();
void av_strndup();
void av_dict_copy();
void avio_context_free();
void avio_open2();
void avcodec_parameters_copy();
void av_int_list_length_for_size();
void av_opt_set_bin();
void avformat_alloc_output_context2();
void avcodec_find_encoder();
void avformat_write_header();
void av_guess_codec();
void av_interleaved_write_frame();
void av_write_trailer();
void avcodec_encode_subtitle();
void avcodec_enum_to_chroma_pos();
void av_strerror();
void avformat_free_context();
void avio_closep();
void ff_ass_subtitle_header_default();
void ff_ass_bprint_text_event();
void ff_ass_add_rect();
void av_bprint_init();
void av_bprint_finalize();

void ff_alloc_dir_entry();
void avio_open_dir();
void avio_read_dir();
void avio_free_directory_entry();
void avio_close_dir();

void av_packet_alloc();
void av_get_sample_fmt_name();
void av_packet_clone();
void av_packet_get_side_data();
void av_packet_free();
void avio_open();
void avcodec_parameters_from_context();
void swr_alloc();
void av_opt_set_int();
void av_opt_set_sample_fmt();
void av_frame_get_buffer();
void swr_get_delay();
void av_frame_make_writable();
void avcodec_send_frame();
void avcodec_receive_packet();
void av_packet_rescale_ts();

void sws_getContext();
void av_default_item_name();
void av_parser_init();
void av_parser_close();
void av_parser_parse2();
void av_parse_time();
void av_frame_get_best_effort_timestamp();
void av_image_get_buffer_size();
void avcodec_decode_video2();
void av_image_fill_arrays();
void av_frame_get_pkt_duration();
void av_opt_free();
void av_application_closep();
void av_opt_set_defaults();
void av_application_open();
void av_application_on_async_statistic();
void av_application_on_async_read_speed();
void av_application_on_io_control();
void avio_find_protocol_name();
void av_md5_alloc();
void av_md5_size();
void av_md5_init();
void av_md5_update();
void av_md5_final();
void ijkav_register_ijkio_protocol();
void ijkav_register_ijklongurl_protocol();
void ijkav_register_ijkhttphook_protocol();
void av_strstart();
void av_stristart();
void av_fifo_alloc();
void ffurl_open_whitelist();
void ffurl_read();
void ffurl_size();
void ffurl_close();
void ffurl_seek();
void ffurl_write();
void ffurl_closep();
void av_fifo_freep();
void av_fifo_size();
void av_fifo_reset();
void av_fifo_space();
void av_fifo_generic_write();
void av_fifo_generic_peek_at();
void av_fifo_drain();
void av_gettime_relative();
void av_stristr();
void av_strlcatf();
void ff_webvtt_secondary_decoder();
// Dummy function export functions from static libraries.

void dummy_main()
{
	av_base64_decode();
	av_base64_encode();
	av_bitstream_filter_init();
	av_bitstream_filter_close();
	av_bitstream_filter_filter();
	av_buffersink_get_frame();
	av_buffersrc_add_frame_flags();
	avfilter_link();
	av_copy_packet();
	av_dict_count();
	av_dict_get();
	av_dict_set();
	av_dict_free();
	av_dump_format();
	av_find_best_stream();
	av_find_default_stream_index();
	av_find_program_from_stream();
	av_frame_alloc();
	av_frame_clone();
	av_frame_free();
	av_frame_is_writable();
	av_frame_alloc();
	av_frame_unref();
	av_free();
	av_freep();
	av_get_bits_per_pixel();
	av_get_bytes_per_sample();
    av_get_bits_per_sample();
	av_get_channel_layout_nb_channels();
	av_get_codec_tag_string();
	av_get_default_channel_layout();
	av_grow_packet();
	av_guess_frame_rate();
	av_guess_sample_aspect_ratio();
	av_image_copy();
	av_init_packet();
	av_log();
	av_log_set_callback();
	av_malloc();
	av_mallocz();
    av_mallocz_array();
	av_new_packet();
	av_packet_copy_props();
	av_packet_ref();
	av_packet_unref();
	av_pix_fmt_count_planes();
	av_pix_fmt_desc_get();
	av_read_frame();
	av_read_pause();
	av_read_play();
	av_rescale();
	av_rescale_q();
	av_rescale_rnd();
    av_rescale_q_rnd();
	av_sample_fmt_is_planar();
	av_samples_get_buffer_size();
	av_seek_frame();
	av_shrink_packet();
	av_strdup();
	avcodec_close();
	avcodec_decode_subtitle2();
	avcodec_find_decoder();
	avcodec_flush_buffers();
	avcodec_get_name();
    avcodec_get_type();
// 	avcodec_profile_name();
	av_get_profile_name();
	avcodec_open2();
	avformat_alloc_context();
	avformat_close_input();
	avformat_find_stream_info();
	avformat_network_init();
	avformat_open_input();
	avformat_seek_file();
	avfilter_inout_alloc();
	avfilter_inout_free();
	avfilter_get_by_name();
	avfilter_graph_alloc();
	avfilter_graph_config();
	avfilter_graph_create_filter();
	avfilter_graph_free();
	avfilter_graph_parse_ptr();
	avio_alloc_context();
	avio_flush();
	avio_size();
	avsubtitle_free();
	ff_check_interrupt();
	ff_add_format();
	ff_isom_write_hvcc();
	ff_isom_write_avcc();
    ff_isom_write_av1c();
	swr_alloc_set_opts();
	swr_convert();
	swr_free();
	swr_init();
	sws_freeContext();
	sws_getCachedContext();
	sws_scale();
// 	ff_draw_init();
// 	ff_draw_color();
// 	ff_blend_mask();

    avcodec_whitelist();
    avcodec_send_packet();
    avcodec_receive_frame();
    avcodec_alloc_context3();
    avcodec_parameters_to_context();
    avcodec_parameters_alloc();
    avcodec_parameters_free();
    avcodec_free_context();
    av_dict_set_int();
    avcodec_profile_name();
    av_codec_set_pkt_timebase();
    ff_urldecode();
    av_md5_sum();
//export the api symbols for mxv
    av_stereo3d_alloc();
    av_stream_add_side_data();
    av_stream_get_side_data();
    av_aes_alloc();
    av_aes_init();
    av_aes_crypt();
    av_sha_alloc();
    av_sha_init();
    av_sha_update();
    av_sha_final();
    av_crc_get_table();
    av_crc();
    avio_read();
    avio_seek();
    avio_rb64();
    avio_rb32();
    avio_r8();
    avio_skip();
    ff_packet_list_get();
    ff_packet_list_free();
    ff_packet_list_put();
    av_packet_new_side_data();
    av_add_index_entry();
    av_index_search_timestamp();
    ff_update_cur_dts();
    av_realloc();
    av_malloc_array();
    av_realloc_array();
    av_lzo1x_decode();
    ffio_limit();
	ffio_fill();
    av_buffer_create();
    av_buffer_realloc();
    av_buffer_unref();
    av_buffer_ref();
    ffio_init_context();
    ff_reduce_index();
    ff_rm_reorder_sipr_data();
    avio_rl32();
    avpriv_report_missing_feature();
    avpriv_dict_set_timestamp();
    avpriv_mpeg4audio_sample_rates();
    avpriv_mpeg4audio_get_config();
    avpriv_split_xiph_headers();
    ff_vorbis_comment();
    avformat_new_stream();
    ff_codec_bmp_tags();
    ff_codec_get_id();
    ff_codec_get_tag();
    ff_get_wav_header();
    ff_codec_movvideo_tags();
    ff_codec_movaudio_tags();
    ff_codec_wav_tags();
    ff_put_wav_header();
    ff_put_bmp_header();
    avio_rb16();
    ff_sipr_subpk_size();
    ff_parse_creation_time_metadata();
    ff_stream_add_bitstream_filter();
    avio_write();
    avio_wl16();
    avio_wl32();
	avio_w8();
    avio_wb16();
    avio_wb32();
    avio_wb64();
    avio_printf();
    avio_write_marker();
	avio_open_dyn_buf();
	avio_get_dyn_buf();
    avio_close_dyn_buf();
	av_lfg_init();
	av_get_random_seed();
    av_fourcc_make_string();
    ff_get_qtpalette();
    avpriv_set_pts_info();
    ff_alloc_extradata();
    av_reduce();
    avcodec_chroma_pos_to_enum();
    av_content_light_metadata_alloc();
    av_stream_new_side_data();
    av_spherical_alloc();
    ff_alloc_extradata();
    avformat_new_stream();
    avpriv_new_chapter();
    av_strlcpy();
    av_strlcat();
	av_strcasecmp();
    ff_metadata_conv();
	ff_metadata_conv_ctx();
    ff_flac_is_native_layout();
    ff_flac_write_header();
    ff_vorbiscomment_length();
    ff_vorbiscomment_write();
    ff_convert_lang_to();
    ff_wv_parse_header();
    ff_avc_parse_nal_units_buf();
    ff_av1_filter_obus_buf();
    av_reallocp();
    av_strndup();
    av_dict_copy();
    avio_context_free();
    avio_open2();
    avcodec_parameters_copy();
    av_int_list_length_for_size();
    av_opt_set_bin();
    avformat_alloc_output_context2();
	avcodec_find_encoder();
	avformat_write_header();
	av_guess_codec();
	av_interleaved_write_frame();
    av_write_trailer();
    avcodec_encode_subtitle();
    avcodec_enum_to_chroma_pos();
	av_strerror();
	avformat_free_context();
	avio_closep();
    ff_ass_subtitle_header_default();
    ff_ass_bprint_text_event();
    ff_ass_add_rect();
    av_bprint_init();
    av_bprint_finalize();

    ff_alloc_dir_entry();
    avio_open_dir();
    avio_read_dir();
    avio_free_directory_entry();
    avio_close_dir();

	av_packet_alloc();
	av_get_sample_fmt_name();
	avio_open();
	avcodec_parameters_from_context();
	swr_alloc();
	av_opt_set_int();
	av_opt_set_sample_fmt();
	av_frame_get_buffer();
	swr_get_delay();
	av_frame_make_writable();
	avcodec_send_frame();
	avcodec_receive_packet();
	av_packet_rescale_ts();
	av_packet_free();
	av_packet_clone();
    av_packet_get_side_data();

	sws_getContext();
	av_default_item_name();
	av_parser_init();
	av_parser_close();
	av_parser_parse2();
    av_parse_time();
	av_frame_get_best_effort_timestamp();

	av_image_get_buffer_size();
    avcodec_decode_video2();
	av_image_fill_arrays();
	av_frame_get_pkt_duration();

    av_opt_free();
    av_application_closep();
    av_opt_set_defaults();
    av_application_open();
    av_application_on_async_statistic();
    av_application_on_async_read_speed();
    av_application_on_io_control();
    avio_find_protocol_name();
    av_md5_alloc();
    av_md5_size();
    av_md5_init();
    av_md5_update();
    av_md5_final();
    ijkav_register_ijkio_protocol();
    ijkav_register_ijklongurl_protocol();
    ijkav_register_ijkhttphook_protocol();
    av_strstart();
    av_stristart();
    av_fifo_alloc();
    ffurl_open_whitelist();
    ffurl_read();
    ffurl_size();
    ffurl_close();
    ffurl_seek();
    ffurl_write();
    ffurl_closep();
    av_fifo_freep();
    av_fifo_size();
    av_fifo_reset();
    av_fifo_space();
    av_fifo_generic_write();
    av_fifo_generic_peek_at();
    av_fifo_drain();
    av_gettime_relative();
    av_stristr();
    av_strlcatf();
    ff_webvtt_secondary_decoder();
}
