/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2025-01-13-58ffbbe39"
#endif /* AVUTIL_FFVERSION_H */
