/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2021-11-11-f6a61947"
#endif /* AVUTIL_FFVERSION_H */
