/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2021-03-01-ba21d2ed"
#endif /* AVUTIL_FFVERSION_H */
